name: Java CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [8, 10]
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
        run: mvn package --file blah8_gui/pom${{ matrix.java }}.xml
